config/routes.rb
FinalProject::Application.routes.draw do
  resources :businesses
  resources :sessions, only: [:new, :create, :destroy]
  resources :menu_items, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'businesses#new',       via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/map',     to: 'static_pages#map',     via: 'get'
  match '/mobile_upload',  to: 'static_pages#mobile_upload',     via: 'get'
  match '/mobile',  to: 'static_pages#mobile',     via: 'get'
  match '/mobile_signin',  to: 'sessions#mobile',     via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @menu_item = current_business.menu_items.build 
      @feed_items = current_business.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def contact
  end



  def map
    @businesses = Business.all
    @business_feed_items = Business.all
    @hash = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      marker.infowindow business.name
      marker.json({ title: business.name, id: business.id })
    end
    #@menu_item = current_business.menu_items.build 
    #@feed_items = current_business.feed.paginate(page: params[:page])
    #@feed_items = Business.find_by(id: params[:id]).feed
    respond_to do |format|
      if request.xhr?
        new_business = Business.find(params[:id])
        @new_menu = new_business.feed
      end
      format.js { render 'map' }
      format.html 
      format.json 
    end
  end

  def mobile #mobile map view prototype


    #DEVELOPMENT IP GENERATION
    a_user_ip = request.remote_ip
      if a_user_ip == "127.0.0.1"
          #b_user_ip = "198.109.0.14" #detroit
          #b_user_ip = "208.80.54.142" #los angeles
          b_user_ip = "112.198.77.65" #manila
      else
          b_user_ip = a_user_ip
      end
    #geocoder search returns an array  
    result = Geocoder.search(b_user_ip).first
    #@result_hash = Gmaps4rails.build_markers(@result) do |result, marker|
    #  marker.lat result.latitude
    #  marker.lng result.longitude
    #  marker.infowindow result.city
    #  marker.json({ title: result.city, id: 555 })
    #end

    @skip_header = true
    @skip_footer = true
    @mobile_body = true
    @businesses = Business.all

    first_loop = 0
    @hash = Gmaps4rails.build_markers(@businesses) do |business, marker|
      if first_loop == 0
        first_loop = 1
        marker.lat result.latitude
        marker.lng result.longitude
        marker.infowindow "You are nearby here"
        marker.json({ title: result.city, id: "user_ip_location" })
      else
        marker.lat business.latitude
        marker.lng business.longitude
        marker.infowindow business.name
        marker.json({ title: business.name, id: business.id })
      end
    end


    @mobile_menu_items = Business.first.feed
    @mobile_business_name = Business.first.name
    respond_to do |format|
      if request.xhr?
        new_business = Business.find(params[:id])
        @new_menu = new_business.feed
        @new_name = new_business.name
      end
      format.js { render 'mobile' }
      format.html 
      format.json 
    end
  end

  def mobile_upload #mobile upload view prototype

    @skip_header = true
    @skip_footer = true
    @mobile_body = true
    if signed_in?
      @menu_item = current_business.menu_items.build 
      @mobile_menu_items = current_business.feed.paginate(page: params[:page])
    else
      #put in a landing page for mobile
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_menu_item_test.html.erb
<li id="<%= infowindow %>">
<p><%= "$" + infowindow.to_s %></p>
</li>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<div class="well is-padded">
	<p>
	  The <%= link_to "GETFULL", map_path, :id => "getfull_link" %>
	web app was made by following, completing, and modifying the 
	<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>.  This app also uses <a href="https://www.heroku.com/">Heroku</a> to deploy and host the web app, <a href="https://github.com/apneadiving/Google-Maps-for-Rails"> Google Maps for Rails </a> to access the Google Maps API, <a href="https://github.com/alexreisner/geocoder"> Geocoder</a> to geocode restaurant addresses, <a href="https://github.com/stympy/faker">Faker</a> to populate a fake database, <a href="https://github.com/thoughtbot/paperclip">Paperclip</a> to manage image uploads, <a href"https://github.com/mislav/will_paginate">will_paginate</a> to paginate long lists, and <a "http://getbootstrap.com/2.3.2/">Twitter Bootstrap</a> for front end development.  
	</p>
	<p>
	All code can be found in Derrick Wolbert's final project <a href="https://github.com/wolberine/final_project">Github respository</a>.
	</p> 
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact

  <%= mail_to("wolbert.derrick@gmail.com", name = "Derrick Wolbert") %>
  via email.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	This page is to assist users in using the web app.
</p>

app/views/static_pages/home.html.erb
 <script src="http://twitter.github.io/bootstrap/dist/js/bootstrap.js"></script>

<% if signed_in? %>
  <div class="row">
    <aside class="span5">
      <section>
        <div id="business_info"><%= render 'shared/business_info' %></div>
      </section>
      <section>
        <%= render 'shared/menu_item_form' %>
      </section>
    </aside>
    <div class="span1"></div>
    <div class="span6">
      <h3>Menu Item Feed</h3>
      <div id="feed_form"><%= render 'shared/feed' %><div>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to <%= link_to "GETFULL", map_path, :id => "getfull_link" %></h1>
    <%= image_tag "coat.png", :id => "image_logo" %>



    <h2>
      This is the home page for the <%= link_to "GETFULL", map_path, :id => "getfull_link" %>, Derrick Wolbert's ECE528 Final Project.
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>

<% end %>

app/views/static_pages/map.html.erb
<% provide(:title, 'Map') %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<!--<h1>Map</h1>
<p>
	Click a map marker to bring up the menu of that restaurant! Click the restaurant name in the sidebar to go to the restaurant's home page!
</p>-->

<div id="gmap_container">
	<div id="map-feed-form-over-map"><%= render partial: 'shared/business_feed_item', collection: @business_feed_items %></div>
	<div id="map" style='width: 100%; height: 100%;'></div>
</div>

<!--<div class="row">
	<div class="span7">	
		<div class="well">
	  		<div id="map" style='width: 100%; height: 400px;'></div>
	  	</div>
	 </div>
	<div class="span5 map-menu-wrapper">
		    <div id="map-feed-form"><%= render partial: 'shared/business_feed_item', collection: @business_feed_items %></div>
	</div> 
</div>-->

<div id="latlong">
This is the latitude and longitude of the active marker. For demo purposes only.
</div>




<% content_for :scripts do %>
<script type="text/javascript">
var handler2 = Gmaps.build('Google');
handler2.buildMap({ provider: { 
	zoom: 1,
	panBy: (500, 50),
	panControl: true,
	panControlOptions: {
		position: google.maps.ControlPosition.TOP_RIGHT
	},
	zoomControl: true,
	zoomControlOptions: {
        style: google.maps.ZoomControlStyle.LARGE,
        position: google.maps.ControlPosition.RIGHT_CENTER
    }
}, internal: {id: 'map'}}, function(){
  // I assume this is the way you retrieve the amrkers array
  var json_data = <%=raw @hash.to_json %>;
  var markers = handler2.addMarkers(json_data);

  _.each(json_data, function(json_marker, index){
      json_marker.marker = markers[index];
      google.maps.event.addListener(json_marker.marker.getServiceObject(), 'click', function( event ){
        var latlong = document.getElementById("latlong");
        latlong.innerHTML =( "Latitude: "+event.latLng.lat()+" "+", longitude: "+event.latLng.lng() );
            $.ajax({
        	url: '/map',
        	type: 'GET',
        	async: false,
        	data: { 
        		title: json_marker.title,
        		id: json_marker.id
        	}
        });

      });
  });
      handler2.bounds.extendWith(markers);
      handler2.fitMapToBounds();

      
});
var targetOffset = $('#map').offset().top - 40;	
$("html, body").delay(2000).animate({scrollTop: targetOffset }, 2000);
</script>
<% end %>

app/views/static_pages/map.js.erb
$("#map-feed-form").html("<%= escape_javascript render :partial => 'shared/map_feed_item' , collection: @new_menu %>");
$("#map-feed-form-over-map").html("<%= escape_javascript render :partial => 'shared/map_feed_item' , collection: @new_menu %>");

app/views/static_pages/mobile.html.erb
<% provide(:title, 'Mobile') %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>



<div id="mobile-gmap_container">
  <a class="btn  btn button" id="button"><i class=icon-list-alt></i></a>
  <a class="btn  btn button2" id="button2"><i class=icon-map-marker></i></a>
  <nav class="menu2" id="menu2" role="navigation2">
    <%= render partial: 'shared/nav_left' %>
  </nav>
  <nav class="menu" id="menu" role="navigation2">
      <%= render partial: 'shared/nav_right' %>
  </nav>

	<!--
  <div id="mobile-map-feed-form-over-map" class="hidden">
    <%= render partial: 'shared/mobile_business_feed_item', collection: @businesses %>
  </div>
  
  <div id="mobile-menu" class="hidden">
    <%= render partial: 'shared/mobile_menu_item', collection: @mobile_menu_items %>
  </div>
   -->
	<div id="mobile-map"></div>

</div>





<% content_for :scripts do %>
<script type="text/javascript">
var handler2 = Gmaps.build('Google');
var json_data = <%=raw @hash.to_json %>;

var user_ip_json_data = <% raw @result_hash.to_json %>

Gmaps.store = {};

handler2.buildMap({ provider: { 
	zoom: 1,
	panBy: (500, 50),
	panControl: true,
	panControlOptions: {
		position: google.maps.ControlPosition.TOP_RIGHT
	},
	zoomControl: true,
	zoomControlOptions: {
        style: google.maps.ZoomControlStyle.LARGE,
        position: google.maps.ControlPosition.RIGHT_CENTER
    }
}, internal: {id: 'mobile-map'}}, function(){
  // I assume this is the way you retrieve the amrkers array

  Gmaps.store.markers = handler2.addMarkers(json_data);

  _.each(json_data, function(json_marker, index){
      json_marker.marker = Gmaps.store.markers[index];
      if (json_marker.id == "user_ip_location"){
        json_marker.marker.getServiceObject().setIcon('https://s3.amazonaws.com/wolberine/google_maps_icons/star-3.png');
      }
      else{
        
        google.maps.event.addListener(json_marker.marker.getServiceObject(), 'click', function( event ){
              $(".button").css("background","#F24C27");  
              $.ajax({
          	url: '/mobile',
          	type: 'GET',
          	async: false,
          	data: { 
          		title: json_marker.title,
          		id: json_marker.id
          	}
          });
        });
      }
  });
      handler2.bounds.extendWith(Gmaps.store.markers);
      handler2.fitMapToBounds();

      
});


//when the business trigger is clicked we check to see if the popout is currently hidden
//based on the hidden we choose the correct animation
/*$('#trigger').click( function() {
    if ($('#mobile-map-feed-form-over-map').hasClass('hidden')) {
        $('#mobile-map-feed-form-over-map').removeClass('hidden');
        showPopout();
    }
    else {
        $('#mobile-map-feed-form-over-map').addClass('hidden');
        hidePopout();
    }
});

function showPopout() {
    $('#mobile-map-feed-form-over-map').animate({
        left: 340
    }, 'fast', function () {
        $('#trigger span').html('Close');  //change the trigger text at end of animation
    });
}

function hidePopout() {
    $('#mobile-map-feed-form-over-map').animate({
        left: -40
    }, 'fast', function () {
        $('#trigger span').html('Show');  //change the trigger text at end of animation
    });
}

//when the menu trigger is clicked we check to see if the popout is currently hidden
//based on the hidden we choose the correct animation
$('#menu-trigger').click( function() {
    if ($('#mobile-menu').hasClass('hidden')) {
        $('#mobile-menu').removeClass('hidden');
        menuShowPopout();
    }
    else {
        $('#mobile-menu').addClass('hidden');
        menuHidePopout();
    }
});

function menuShowPopout() {
    $('#mobile-menu').animate({
        right: 0
    }, 'fast', function () {
        $('#menu-trigger span').html('Close');  //change the trigger text at end of animation
    });
}

function menuHidePopout() {
    $('#mobile-menu').animate({
        right: -340
    }, 'fast', function () {
        $('#menu-trigger span').html('Show');  //change the trigger text at end of animation
    });
}
*/
//begin business list jquery on click events to generate new menu
function dynamicEvent() {
  link_id = this.id;
  
  //$.ajax({
  //        url: '/mobile',
  //        type: 'GET',
  //        async: false,
  //        data: { 
  //          id: link_id
  //        }
  //});
  
  $(".button").css("background","#F24C27");
_.each(json_data, function(json_marker, index){
      json_marker.marker = Gmaps.store.markers[index];
        if (json_marker.id == link_id){
          googleMarker = json_marker.marker.getServiceObject();
          google.maps.event.trigger(googleMarker, 'click');
        }
  });
}



var button2=document.getElementById("button2");
button2.onclick = function(){
  $(".menu2").css("left","0");
};

var button2_in=document.getElementById("button2_in");
button2_in.onclick = function(){
  $(".menu2").css("left","-300px");
};

var button=document.getElementById("button");
button.onclick = function(){
  $(".menu").css("right","0");
};

var button_in=document.getElementById("button_in");
button_in.onclick = function(){
  $(".menu").css("right","-300px");
  $(".button").css("background","#fff");
};


var menu2 = document.getElementById("menu2");
var links = menu2.getElementsByTagName('div');
for (var i = 0; i < links.length - 1; i++) {
  var link = links[i];
  //if ($(link).hasClass('menu_scroll')){
    link.onclick = dynamicEvent;
  //}
}


      //#moves map to marker clicked + open infowindow
      //$(document).on 'click', '#mobile_business_feed_item', -> alert('hi');
        //markers[$(this).data('marker')].panTo()
        //markers[$(this).data('marker')].click()


</script>
<% end %>

app/views/static_pages/mobile.js.erb
$("#mobile_menu_container").html("<%= escape_javascript render :partial => 'shared/mobile_menu_item' , collection: @new_menu %>");
$("#mobile_business_name").html("<%= @new_name %>");

app/views/static_pages/mobile_upload.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<% if signed_in? %>

<div class="bottom-buffer">
  <div class="text-center row snap_button_wrapper" id="snap_button_wrapper">
    	<button class="btn row btn-primary btn-xlarge" id="file_upload_spoof"><i class="icon-white icon-camera"></i>Add a menu item!</button>	
  </div>


  <div class="text-center previewContainer">
      <img id="imgPreview" src="#" alt="your image"/>
  </div>

</div>

<nav class="mobile_menu_wrapper" role="navigation">
  <div class="side-buffers">
  	<%= form_for @menu_item, :html => { :multipart => true }  do |f| %>
    		<%= render 'shared/error_messages', object: f.object %>
      	<%= f.text_area :name, placeholder: "Enter menu item name", :class => "top-buffer" %>
    		<div class="field">
      		<%= f.text_area :description, placeholder: "Compose new menu item description..." %>
    		</div>
      	<%= f.text_area :price, placeholder: "Enter menu item price" %>
      	<div id="photo_attachment_container">
    			<div class="photo_wrapper">
    				<div class="file_upload_wrapper"> 
      				<%= f.file_field :photo, :style => "hidden", :id => "imgInp" %>
      			</div>
      		</div>
      	</div>
    		<div class="text-center">
      			<%= f.submit "Post", class: "btn-xlarge post_button" %>
    		</div>
        <a class="btn btn button3 pull-right" id="button3"><i class="icon-black icon-remove"></i></a>
    <% end %>
  </div>
 
</nav>

<nav class="menu3" id="menu3" role="navigation2">
    <%= render partial: 'shared/nav_bottom' %>
</nav>

  <!--<nav class="menu3" id="menu3" role="navigation2">
      <%= render partial: 'shared/nav_right' %>
  </nav>
  <a class="btn  btn button" id="button"><i class=icon-list-alt></i></a>-->

<% else %>
  <div><%= @user_ip %></div>
  <div><%= @result %></div>

<% end %>

<script>
//$( document ).ready(function() {
	
//});
//make the menu item description div not as high so the snap button has more room.  even better, figure out how to display image before upload


$( "#file_upload_spoof").click(
  function(){
    $( "input:file" ).click()
    }
  );

  $(function() {
     $("input:file").change(function (){
       //$( "#file_upload_spoof" ).removeClass("btn-primary").addClass("btn-success");   
      //$( ".snap_button_wrapper" ).remove();  
      $( "#snap_button_wrapper" ).css('display','none');  
       $(".mobile_menu_wrapper").css("bottom","0");
       $('#imgPreview').css('display','');   

       //$(".snap_button_wrapper").css("margin-top","20px");
       //$( "#file_upload_spoof").html("<i class='icon-white icon-camera'></i> Change Picture");            
     });
  });



function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imgPreview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
    }
}

$("#imgInp").change(function(){
    readURL(this);
});


var button3=document.getElementById("button3");
button3.onclick = function(){
  $(".mobile_menu_wrapper").css("bottom","-400px");
  $( "#snap_button_wrapper" ).css('display','');
  $('#imgPreview').css('display','none');

  //src is broken on mobile chromePICK UP HERE
};


</script>