config/routes.rb
FinalProject::Application.routes.draw do
  resources :businesses
  resources :sessions, only: [:new, :create, :destroy]
  resources :menu_items, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'businesses#new',       via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/map',     to: 'static_pages#map',     via: 'get'
  match '/mobile_upload',  to: 'static_pages#mobile_upload',     via: 'get'
  match '/mobile',  to: 'static_pages#mobile',     via: 'get'
  match '/mobile_signin',  to: 'sessions#mobile',     via: 'get'

end

app/views/layouts/_body.html.erb
  <body>
    <%= render 'layouts/header' unless @skip_header %>
    <div class="container" id="scroll_id">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= yield :scripts %>
      <%= render 'layouts/footer' unless @skip_footer %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
  </body>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "GETFULL", root_path %> web app
    by Derrick Wolbert
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "GetFull", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li class><%= link_to "Home", root_path %></li>
          <li><%= link_to "Map", map_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Businesses", businesses_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_business %></li>
                <li><%= link_to "Settings", edit_business_path(current_business) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_mobile_body.html.erb
  <body id="mobile">
    <%= render 'layouts/header' unless @skip_header %>
      <%= yield %>
      <%= yield :scripts %>
      <%= render 'layouts/footer' unless @skip_footer %>
      <!--<%= debug(params) if Rails.env.development? %>-->
  </body>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
    <%= render 'layouts/body' unless @mobile_body %>
    <%= render 'layouts/mobile_body' if @mobile_body%>
</html>